"""Finger (caging-gripper) catch isolation test — M6.

The honest successor to arm_catch_solo's force-limited constraint ("foam
stick"). Here the catch is *physical*: a 3-finger gripper (URDF generated by
assets/make_gripper_urdf.py) closes around the ball, and the ball is held by
caging geometry + pad friction — NO constraint, no glue. This tests whether
a contact-based catch is actually feasible at our arrival speeds, which is
the real sim2real question.

Mechanism:
  1. Catcher tracks the ball to the intercept (same as arm_catch_solo:
     predict landing, position body so EE meets the ball at the
     velocity-matched shoulder angle, absorption sweep to cut rel-vel).
  2. Fingers start splayed OPEN (wide mouth).
  3. When the ball enters the gripper volume (d < CLOSE_DIST), close the
     fingers: they curl inward at servo speed with a torque cap, so they
     wrap and squeeze rather than crush.
  4. Retention is friction + caging. We verify the ball is still held
     (≥2 fingers touching, ball near palm, low rel-vel) after settling
     AND after a small lift (proves friction beats gravity + accel).

Acceptance: caught AND retained through the lift.

Usage:
    python tests/finger_catch_solo.py --headless --runs-dir runs/fingers
    python tests/finger_catch_solo.py --headless --grid
    python tests/finger_catch_solo.py --headless --vx 4.5 --vz -3.2
"""
from __future__ import annotations
import argparse
import sys
import os
import math
import numpy as np
import pybullet as p

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from sim_setup import (Logger, MarkerSet, Marker, VideoRecorder, Sim,
                       make_world, make_solo_drone, auto_run_paths,
                       rotate_runs, DT)
from config import DEFAULT as DEFAULT_GAME
from drone import ASSETS
from ball import spawn_ball, state as ball_state, predict_landing

# Reuse the validated launch math, geometry, and catch-task gains.
from arm_catch_solo import (
    G, L_ARM, EE_INTERCEPT_X, EE_INTERCEPT_Z, SHOULDER_CATCH,
    T_ABSORB_MIN, OMEGA_S, SWEEP_MARGIN, CATCH_KP, CATCH_KD,
    launch_state_for_intercept,
)

GRIPPER_URDF = os.path.join(ASSETS, "quadrotor_gripper.urdf")

BALL_VX_DEFAULT = 3.3
BALL_VZ_DEFAULT = -3.2

# Finger catch
# Heavier gripper ~doubles the arm's rotational inertia, so the velocity-
# matched sweep lags; start it earlier than the plain-arm optimum (1.0).
FINGER_SWEEP_MARGIN = 1.0
# The catch happens in the finger CUP, ~CUP_DEPTH beyond the end_effector
# link (the forearm tip). Position the body using an effective arm length so
# the cup center — not the palm rim — lands on the ball.
CUP_DEPTH = 0.04   # caging sweet spot beyond the EE (verified: fingers
                   # converge ~4 cm out; deeper and the ball falls through
                   # behind them). See docs/iteration_findings.md §13.
L_EFF = L_ARM + CUP_DEPTH
CLOSE_DIST = 0.13       # m — start closing when ball this close to the EE
BALL_RESTITUTION = 0.10 # foam-lined: low bounce
BALL_FRICTION = 1.4
PAD_FRICTION = 1.4
HOLD_DIST = 0.10        # acceptance: ball within this of palm at end
HOLD_REL_VEL = 0.5

SETTLE_S = 2.5   # long enough for the position integrator to null the
                 # gripper COM-offset hover error before the ball is launched


def run(gui, runs_dir, ball_vx=BALL_VX_DEFAULT, ball_vz=BALL_VZ_DEFAULT,
        verbose=True):
    log_path, video_path = auto_run_paths(runs_dir)
    make_world(DEFAULT_GAME, gui=gui)

    shoulder_at_catch = -math.atan2(-ball_vz, ball_vx)
    sweep_dtheta = shoulder_at_catch - SHOULDER_CATCH
    t_absorb = max(T_ABSORB_MIN, FINGER_SWEEP_MARGIN * 2.0 * sweep_dtheta / OMEGA_S)

    intercept = np.array([EE_INTERCEPT_X, 0.0, EE_INTERCEPT_Z])
    catcher_home = np.array([
        EE_INTERCEPT_X - L_EFF * math.sin(shoulder_at_catch),
        0.0,
        EE_INTERCEPT_Z + L_EFF * math.cos(shoulder_at_catch),
    ])

    catcher = make_solo_drone(tuple(catcher_home), play_extent=(4.0, 4.0, 1.2),
                              urdf_path=GRIPPER_URDF)
    catcher.set_target(catcher_home)
    catcher.arm_reaction_ff = True
    catcher.attitude_gain_schedule = True
    catcher.arm_translational_ff_z = True
    catcher.controller.max_tilt_deg = 60.0
    catcher.controller.kp = CATCH_KP.copy()
    catcher.controller.kd = CATCH_KD.copy()
    # Position integral nulls the gripper's COM-offset hover error (~12 cm),
    # which would otherwise become the EE-to-ball miss at the catch.
    catcher.controller.kI_pos = np.array([20.0, 20.0, 20.0])
    # Yaw integral nulls the gripper's steady yaw offset (~18°): the finger
    # motors leave a small persistent yaw torque, and the arm points in -x so
    # any yaw swings the EE out in y. Default attitude kI has zero yaw term.
    catcher.controller.kI = catcher.controller.kI.copy()
    catcher.controller.kI[2] = 0.3
    catcher.hold_arm(SHOULDER_CATCH, 0.0)
    catcher.open_gripper()
    catcher.set_finger_dynamics(lateral_friction=PAD_FRICTION,
                                restitution=BALL_RESTITUTION)

    markers = MarkerSet()
    markers.intent.set(intercept.tolist())
    m_pred = Marker([0.1, 0.9, 1.0, 0.9], radius=0.05)
    logger = Logger(log_path, decimate=2)
    video = VideoRecorder(video_path, every=8, eye=(0.5, -3.0, 1.8),
                          target=(0.5, 0.0, 1.3), fov=70)
    sim = Sim([catcher], markers, logger, video, gui=gui)

    for _ in range(int(SETTLE_S / DT)):
        sim.tick("settle")

    launch_pos, launch_vel, t_flight = launch_state_for_intercept(
        intercept, (ball_vx, 0.0, ball_vz))
    if verbose:
        print(f"intercept={intercept.tolist()} shoulder@catch="
              f"{math.degrees(shoulder_at_catch):.1f}° t_flight={t_flight:.3f}s")
    ball = spawn_ball(launch_pos)
    p.changeVisualShape(ball, -1, rgbaColor=[1.0, 0.3, 0.3, 1])
    p.changeDynamics(ball, -1, linearDamping=0.0, angularDamping=0.0,
                     restitution=BALL_RESTITUTION, lateralFriction=BALL_FRICTION)
    p.resetBaseVelocity(ball, linearVelocity=launch_vel.tolist())

    absorbing = False
    closing = False     # fingers commanded to curl (still tracking the ball)
    captured = False    # fingers have actually grabbed (≥2 touching) → hold
    result = {
        "vx": ball_vx, "vz": ball_vz, "speed": math.hypot(ball_vx, ball_vz),
        "closed": False, "caught": False, "held": False,
        "close_t": None, "close_d": None, "close_rel": None,
        "max_fingers": 0, "min_d": 1e9,
    }
    trace = []
    timeout_s = t_flight + 2.5
    lift_started = None

    for i in range(int(timeout_s / DT)):
        t = i * DT
        bp, bv = ball_state(ball)
        ee = catcher.gripper_world_position()
        ee_v = catcher.gripper_world_velocity()
        d = float(np.linalg.norm(ee - bp))
        rel = float(np.linalg.norm(bv - ee_v))
        nf = catcher.fingers_touching(ball)
        result["max_fingers"] = max(result["max_fingers"], nf)
        if d < result["min_d"]:
            result["min_d"] = d
            result["_dbg"] = (
                f"body={np.round(catcher.position(),3).tolist()} "
                f"tgt={np.round(catcher.target,3).tolist()} "
                f"EE={np.round(ee,3).tolist()} ball={np.round(bp,3).tolist()} "
                f"shoulder={math.degrees(catcher.joint_states()[0]):.0f}deg")

        a, b, c = -0.5 * G, bv[2], bp[2] - EE_INTERCEPT_Z
        disc = b * b - 4 * a * c
        t_int = None
        if disc >= 0:
            sq = math.sqrt(disc)
            roots = [r for r in [(-b + sq) / (2 * a), (-b - sq) / (2 * a)] if r > 1e-3]
            if roots:
                t_int = max(roots)

        if nf >= 2:
            captured = True   # latch: fingers have the ball

        if captured:
            # Post-catch: brake shoulder, hold (then lift). Fingers keep
            # squeezing via _apply_gripper.
            phase = "hold"
            if lift_started is None:
                lift_started = t
                result["close_t"] = result["close_t"] or t
            elapsed = t - lift_started
            if elapsed > 0.4:
                # Lift 30 cm to test that friction holds against gravity+accel.
                phase = "lift"
                tgt = catcher_home + np.array([0, 0, min(0.3, (elapsed - 0.4) * 0.5)])
                catcher.set_target(tgt, vel=(0, 0, 0))
            else:
                catcher.set_target(catcher.position(), vel=(0, 0, 0))
            catcher.spin_arm(0.0, 0.0)
        elif absorbing:
            # Latched: keep sweeping and hold the last body target even when
            # predict_landing fails (ball dropped below the EE plane in the
            # final ~50 ms). Never reset to home mid-catch.
            if t_int is not None:
                prog = max(0.0, min(1.0, 1.0 - t_int / t_absorb))
                catcher.spin_arm(OMEGA_S * prog, 0.0)
            else:
                catcher.spin_arm(OMEGA_S, 0.0)
            phase = "absorb"
        else:
            predicted_xy, _ = predict_landing(bp, bv, EE_INTERCEPT_Z)
            if predicted_xy is not None:
                m_pred.set([predicted_xy[0], predicted_xy[1], EE_INTERCEPT_Z])
                bx = -L_EFF * math.sin(shoulder_at_catch)
                body_target = np.array([predicted_xy[0] + bx, predicted_xy[1],
                                        catcher_home[2]])
                if t_int is not None and t_int <= t_absorb:
                    absorbing = True
                    prog = max(0.0, min(1.0, 1.0 - t_int / t_absorb))
                    catcher.set_target(body_target, vel=(0, 0, 0))
                    catcher.spin_arm(OMEGA_S * prog, 0.0)
                    phase = "absorb"
                else:
                    catcher.set_target(body_target, vel=(0, 0, 0))
                    catcher.hold_arm(SHOULDER_CATCH, 0.0)
                    phase = "track"
            else:
                catcher.set_target(catcher_home, vel=(0, 0, 0))
                catcher.hold_arm(SHOULDER_CATCH, 0.0)
                phase = "wait"

        # Finger close: start curling as the ball enters the gripper volume,
        # but KEEP tracking/absorbing so the EE stays with the ball while the
        # fingers wrap (freezing the EE here lets the ball sail past).
        if not closing and d < CLOSE_DIST:
            catcher.close_gripper()
            closing = True
            result.update(closed=True, close_d=d, close_rel=rel)
            if verbose:
                print(f"[t={t:.3f}s] CLOSE  d={d*100:.1f}cm rel={rel:.2f}m/s")

        trace.append({"t": t, "phase": phase, "d": d, "rel": rel, "nf": nf,
                      "ball_z": bp[2], "ee_z": ee[2]})
        sim.tick(phase, extra_payload={
            "ee_to_ball": d, "rel_vel": rel, "fingers": nf,
            "ball_pos": bp.tolist(), "ee_pos": ee.tolist()})

        # End conditions
        if captured and result["close_t"] is not None and t - result["close_t"] > 1.6:
            break
        if not captured and bp[2] < 0.05:
            break
        if closing and not captured and bp[2] < EE_INTERCEPT_Z - 0.35:
            break   # ball fell well past the gripper, uncaught

    bp, bv = ball_state(ball)
    ee = catcher.gripper_world_position()
    ee_v = catcher.gripper_world_velocity()
    end_d = float(np.linalg.norm(ee - bp))
    end_rel = float(np.linalg.norm(bv - ee_v))
    nf = catcher.fingers_touching(ball)
    result["captured"] = captured
    result["caught"] = bool(captured and end_d < HOLD_DIST and nf >= 2)
    result["held"] = bool(result["caught"] and end_rel < HOLD_REL_VEL)
    result["end_d"] = end_d
    result["end_rel"] = end_rel
    result["end_fingers"] = nf

    sim.logger.close()
    sim.video.close()

    if verbose:
        print("\n=== RESULT ===")
        print(f"closed: {result['closed']}  caught: {result['caught']}  "
              f"held: {result['held']}")
        print(f"end: d={end_d*100:.1f}cm rel={end_rel:.2f}m/s "
              f"fingers_touching={nf}  max_fingers={result['max_fingers']}")
        last = None
        print("Phase transitions:")
        for r in trace:
            if r["phase"] != last:
                print(f"  t={r['t']:.3f} -> {r['phase']:7s} d={r['d']*100:.1f}cm "
                      f"rel={r['rel']:.2f} nf={r['nf']} ball_z={r['ball_z']:.3f}")
                last = r["phase"]
        if result["close_t"] is not None:
            print("Close-window trace:")
            for r in trace:
                if -0.05 < r["t"] - result["close_t"] < 0.5 and int(r["t"]*240) % 3 == 0:
                    print(f"  t={r['t']:.3f} {r['phase']:7s} d={r['d']*100:5.1f}cm "
                          f"rel={r['rel']:4.2f} nf={r['nf']} "
                          f"ball_z={r['ball_z']:.3f} ee_z={r['ee_z']:.3f}")

    if runs_dir:
        rotate_runs(__import__("pathlib").Path(runs_dir), keep=5)
    return result


def run_grid():
    cells = [(vx, vz) for vx in [2.5, 3.3, 4.5, 5.5] for vz in [-2.0, -3.2, -4.5]]
    results = []
    print(f"{'vx':>5} {'vz':>5} {'spd':>5} | {'closed':>6} {'caught':>6} "
          f"{'held':>5} {'rel@close':>9} {'maxF':>4} {'endF':>4}")
    for vx, vz in cells:
        p.connect(p.DIRECT)
        try:
            r = run(gui=False, runs_dir=None, ball_vx=vx, ball_vz=vz, verbose=False)
        finally:
            p.disconnect()
        results.append(r)
        rel_s = f"{r['close_rel']:9.2f}" if r["close_rel"] is not None else "     miss"
        print(f"{vx:5.1f} {vz:5.1f} {r['speed']:5.2f} | {str(r['closed']):>6} "
              f"{str(r['caught']):>6} {str(r['held']):>5} {rel_s} "
              f"{r['max_fingers']:>4} {r['end_fingers']:>4}")
    held = sum(1 for r in results if r["held"])
    print(f"\nheld {held}/{len(results)}")
    return 0 if held == len(results) else 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--headless", action="store_true")
    ap.add_argument("--runs-dir", default=None)
    ap.add_argument("--grid", action="store_true")
    ap.add_argument("--vx", type=float, default=BALL_VX_DEFAULT)
    ap.add_argument("--vz", type=float, default=BALL_VZ_DEFAULT)
    args = ap.parse_args()
    if args.grid:
        return run_grid()
    gui = not args.headless
    p.connect(p.GUI if gui else p.DIRECT)
    try:
        r = run(gui=gui, runs_dir=args.runs_dir, ball_vx=args.vx, ball_vz=args.vz)
        return 0 if r["held"] else 1
    finally:
        p.disconnect()


if __name__ == "__main__":
    sys.exit(main())
