#!/usr/bin/env python3
"""Generate `quadrotor_tv_gripper.urdf`: the thrust-vectoring variant of the
caging-gripper drone.

Identical to `quadrotor_gripper.urdf` (base + 2-link arm + 4x3 caging hand)
EXCEPT each cosmetic prop disk now hangs off a **radial tilt joint**: a
revolute joint whose hinge axis is the *tangential* direction at that rotor,
so a positive joint angle nods the rotor's thrust toward/away from the hub
(i.e. the horizontal thrust component points *radially*, through the hub).
See docs/concepts/12 + iteration_findings §22.

This generator is intentionally **self-contained** (it inlines the base / arm /
finger geometry rather than importing make_gripper_urdf, which lives outside
version control in this project) so the thrust-vectoring branch is standalone.
The arm + finger blocks are copied verbatim from make_gripper_urdf.py — keep
them in sync if that geometry changes.

A NOTE ON THE HINGE AXIS (the one place the design docs slip): concepts/12
calls this "radial tilt" and at one point writes "hinge axis along the arm".
Taken literally, a hinge *along* the arm (radial axis) would tip the thrust
*tangentially* (sideways across the arm) and produce a pure-yaw force — the
exact "tangential" option the doc rejects. The load-bearing, testable property
(radial horizontal force => zero moment arm => zero yaw torque, U2) requires
the hinge axis to be **tangential** (perpendicular to the arm, horizontal).
Every other claim in the doc — "nods toward/away from hub", "horizontal thrust
along the arm", wash plane through the body center (x+y=0) — is consistent with
a tangential hinge / radial force. So we hinge tangentially; see
ThrustVectoringDrone for the matching force model.

The rotor disks stay near-massless and cosmetic: the controller applies each
rotor's thrust analytically (force vector at the rotor position), and only
*drives the tilt joint kinematically* so the rendered disk visibly tilts. The
joint never carries dynamic load (same treatment the props always had).

Run:  python assets/make_tv_gripper_urdf.py
"""
import math
import os

# ------- geometry copied from make_gripper_urdf.py (keep in sync) -------
N_FINGERS = 4
MOUNT_R = 0.034
SEG_LENS = (0.055, 0.032, 0.025)
FINGER_HALF = 0.007
PAD_FRICTION = 1.4

HEADER = '''<?xml version="1.0"?>
<!-- GENERATED by assets/make_tv_gripper_urdf.py - do not edit by hand. -->
<robot name="quadrotor_tv_gripper">
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.546"/>
      <inertia ixx="0.0025" ixy="0" ixz="0" iyy="0.0025" iyz="0" izz="0.0044"/>
    </inertial>
    <visual>
      <geometry><box size="0.18 0.18 0.04"/></geometry>
      <material name="body"><color rgba="0.15 0.15 0.18 1"/></material>
    </visual>
    <collision>
      <geometry><box size="0.18 0.18 0.04"/></geometry>
    </collision>
  </link>
'''

ARM = '''
  <link name="shoulder_housing">
    <inertial><mass value="0.010"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/></inertial>
    <visual><geometry><cylinder radius="0.020" length="0.020"/></geometry>
      <material name="hub"><color rgba="0.30 0.30 0.30 1"/></material></visual>
  </link>
  <joint name="j_shoulder_mount" type="fixed">
    <parent link="base_link"/><child link="shoulder_housing"/>
    <origin xyz="0 0 0.030"/>
  </joint>

  <link name="upper_arm">
    <inertial>
      <origin xyz="0 0 -0.10"/>
      <mass value="0.030"/>
      <inertia ixx="1.0e-4" ixy="0" ixz="0" iyy="1.0e-4" iyz="0" izz="1.0e-6"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.10"/>
      <geometry><cylinder radius="0.008" length="0.20"/></geometry>
      <material name="arm_upper"><color rgba="0.9 0.6 0.1 1"/></material>
    </visual>
  </link>
  <joint name="shoulder_joint" type="revolute">
    <parent link="shoulder_housing"/><child link="upper_arm"/>
    <origin xyz="0 0 -0.010"/>
    <axis xyz="0 -1 0"/>
    <limit lower="-100" upper="100" effort="2.0" velocity="20"/>
    <dynamics damping="0.005" friction="0.001"/>
  </joint>

  <link name="forearm">
    <inertial>
      <origin xyz="0 0 -0.10"/>
      <mass value="0.030"/>
      <inertia ixx="1.0e-4" ixy="0" ixz="0" iyy="1.0e-4" iyz="0" izz="1.0e-6"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.10"/>
      <geometry><cylinder radius="0.008" length="0.20"/></geometry>
      <material name="arm_lower"><color rgba="0.1 0.6 0.9 1"/></material>
    </visual>
  </link>
  <joint name="elbow_joint" type="revolute">
    <parent link="upper_arm"/><child link="forearm"/>
    <origin xyz="0 0 -0.20"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="3.2" effort="2.0" velocity="20"/>
    <dynamics damping="0.005" friction="0.001"/>
  </joint>

  <link name="end_effector">
    <inertial><mass value="0.005"/>
      <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/></inertial>
    <visual><geometry><sphere radius="0.012"/></geometry>
      <material name="ee"><color rgba="0.10 0.95 0.25 1"/></material></visual>
    <collision><geometry><sphere radius="0.012"/></geometry></collision>
  </link>
  <joint name="j_ee" type="fixed">
    <parent link="forearm"/><child link="end_effector"/>
    <origin xyz="0 0 -0.20"/>
  </joint>
'''

# Quadrant (X) rotor layout — unchanged positions (decision: §22). z = 0.025 to
# match the original prop disk height.
ROTOR_Z = 0.025
ROTORS = [
    ("fl", 0.10, 0.10, "0.8 0.2 0.2 0.8"),
    ("fr", 0.10, -0.10, "0.2 0.2 0.8 0.8"),
    ("bl", -0.10, 0.10, "0.2 0.2 0.8 0.8"),
    ("br", -0.10, -0.10, "0.8 0.2 0.2 0.8"),
]
TILT_LIMIT = 1.2   # rad, generous; the controller clamps to its own beta_max


def finger_block(idx, phi):
    """One M-segment finger at azimuth phi around the -z (palm) axis (verbatim
    from make_gripper_urdf.py)."""
    c, s = math.cos(phi), math.sin(phi)
    mx, my = MOUNT_R * c, MOUNT_R * s
    ax, ay = -s, c
    half = FINGER_HALF
    masses = [0.004, 0.0035, 0.003, 0.0025]
    colors = ["0.85 0.85 0.20 1", "0.95 0.55 0.10 1",
              "0.20 0.45 0.95 1", "0.6 0.3 0.8 1"]
    out = []
    for k, L in enumerate(SEG_LENS):
        link = f"finger{idx}_seg{k}"
        parent = "forearm" if k == 0 else f"finger{idx}_seg{k-1}"
        origin = (f"{mx:.4f} {my:.4f} -0.20" if k == 0
                  else f"0 0 {-SEG_LENS[k-1]:.4f}")
        m = masses[min(k, len(masses) - 1)]
        col = colors[min(k, len(colors) - 1)]
        out.append(f'''
  <link name="{link}">
    <inertial><origin xyz="0 0 {-L/2:.4f}"/><mass value="{m}"/>
      <inertia ixx="3e-6" ixy="0" ixz="0" iyy="3e-6" iyz="0" izz="1e-6"/></inertial>
    <visual><origin xyz="0 0 {-L/2:.4f}"/>
      <geometry><box size="{2*half:.3f} {2*half:.3f} {L:.3f}"/></geometry>
      <material name="seg{idx}{k}"><color rgba="{col}"/></material></visual>
    <collision><origin xyz="0 0 {-L/2:.4f}"/>
      <geometry><box size="{2*half:.3f} {2*half:.3f} {L:.3f}"/></geometry></collision>
  </link>
  <joint name="{link}_joint" type="revolute">
    <parent link="{parent}"/><child link="{link}"/>
    <origin xyz="{origin}"/>
    <axis xyz="{ax:.4f} {ay:.4f} 0"/>
    <limit lower="-0.8" upper="2.0" effort="0.6" velocity="15"/>
    <dynamics damping="0.002" friction="0.001"/>
  </joint>''')
    return "".join(out)


def tilt_rotor_block(name, x, y, col):
    """A radial tilt joint + its cosmetic rotor disk.

    Hinge axis = tangential unit (-y, x, 0)/|.| so +angle nods the disk normal
    (body +z) toward the +radial direction (away from the hub). The disk visual
    sits at the joint origin (local 0,0,0); when the joint rotates the whole
    disk tips, which is the visual cue for the tilt servo.
    """
    norm = math.hypot(x, y)
    ax, ay = -y / norm, x / norm          # tangential hinge axis
    return f'''
  <link name="rotor_{name}">
    <inertial><mass value="0.001"/><inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/></inertial>
    <visual>
      <origin xyz="0 0 0"/>
      <geometry><cylinder radius="0.04" length="0.005"/></geometry>
      <material name="rotor_{name}_m"><color rgba="{col}"/></material>
    </visual>
  </link>
  <joint name="tilt_{name}_joint" type="revolute">
    <parent link="base_link"/><child link="rotor_{name}"/>
    <origin xyz="{x} {y} {ROTOR_Z}"/>
    <axis xyz="{ax:.4f} {ay:.4f} 0"/>
    <limit lower="{-TILT_LIMIT}" upper="{TILT_LIMIT}" effort="2.0" velocity="20"/>
    <dynamics damping="0.001" friction="0.0"/>
  </joint>
'''


def main():
    props = "".join(tilt_rotor_block(n, x, y, c) for n, x, y, c in ROTORS)
    parts = [HEADER, props, ARM]
    for i in range(N_FINGERS):
        parts.append(finger_block(i, 2 * math.pi * i / N_FINGERS + math.pi / 2))
    parts.append("</robot>\n")
    out = os.path.join(os.path.dirname(__file__), "quadrotor_tv_gripper.urdf")
    with open(out, "w") as f:
        f.write("".join(parts))
    print(f"wrote {out}  (4 radial-tilt rotors, {N_FINGERS} fingers x "
          f"{len(SEG_LENS)} segments, pad friction {PAD_FRICTION})")


if __name__ == "__main__":
    main()
