#!/usr/bin/env python3
"""Generate `quadrotor_gripper.urdf`: the standard quadrotor + 2-link arm,
but with the end-effector sphere replaced by an N-finger caging gripper.

Why a generator instead of a hand-written URDF: the finger geometry (count,
length, mount radius, segment split, splay) is exactly what we tune while
testing whether a *contact-based* catch is feasible. One constant change +
regenerate beats editing N symmetric XML blocks by hand.

Geometry (forearm-tip / "palm" frame, z down the arm, -z = outward):
  - A small `end_effector` sphere stays at the forearm tip as the palm
    center, so existing ee_link positioning code is unchanged.
  - N fingers mount on a ring of radius MOUNT_R around the -z axis.
  - Each finger = M segments (human-like). A LONG proximal phalanx reaches
    down past the ball's equator; the shorter middle + distal segments curl
    UNDER the ball to meet beneath it — form closure, not just a pinch. This
    is what survives full inversion (a 2-segment finger could not — it folded
    back over the wrist). See docs/iteration_findings.md §15.

Joint sign convention: angle 0 = segment points straight down (-z),
positive = curl inward (fingertips converge), negative = splay outward
(wide mouth to receive the ball).

Run:  python assets/make_gripper_urdf.py
"""
import math
import os

N_FINGERS = 4
MOUNT_R = 0.034          # m, palm ring radius (>= ball radius 0.03 so fingers
                         # start OUTSIDE the ball and can wrap around it)
# Segment lengths from palm outward: long proximal, then shorter middle +
# distal that curl under. Validated as a form-closure cage (inversion test).
SEG_LENS = (0.055, 0.032, 0.025)
FINGER_HALF = 0.007      # m, finger half-thickness (box cross-section)
PAD_FRICTION = 1.4       # lateral friction of finger pads (rubber-ish)

HEADER = '''<?xml version="1.0"?>
<!-- GENERATED by assets/make_gripper_urdf.py - do not edit by hand. -->
<robot name="quadrotor_gripper">
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.546"/>
      <inertia ixx="0.0025" ixy="0" ixz="0" iyy="0.0025" iyz="0" izz="0.0044"/>
    </inertial>
    <visual>
      <geometry><box size="0.18 0.18 0.04"/></geometry>
      <material name="body"><color rgba="0.15 0.15 0.18 1"/></material>
    </visual>
    <collision>
      <geometry><box size="0.18 0.18 0.04"/></geometry>
    </collision>
  </link>
'''

PROPS = ""
for name, x, y, col in [("arm_fl", 0.10, 0.10, "0.8 0.2 0.2 0.8"),
                        ("arm_fr", 0.10, -0.10, "0.2 0.2 0.8 0.8"),
                        ("arm_bl", -0.10, 0.10, "0.2 0.2 0.8 0.8"),
                        ("arm_br", -0.10, -0.10, "0.8 0.2 0.2 0.8")]:
    PROPS += f'''
  <link name="{name}">
    <inertial><mass value="0.001"/><inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/></inertial>
    <visual>
      <origin xyz="{x} {y} 0.025"/>
      <geometry><cylinder radius="0.04" length="0.005"/></geometry>
      <material name="{name}_m"><color rgba="{col}"/></material>
    </visual>
  </link>
  <joint name="j_{name}" type="fixed"><parent link="base_link"/><child link="{name}"/></joint>
'''

ARM = '''
  <link name="shoulder_housing">
    <inertial><mass value="0.010"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/></inertial>
    <visual><geometry><cylinder radius="0.020" length="0.020"/></geometry>
      <material name="hub"><color rgba="0.30 0.30 0.30 1"/></material></visual>
  </link>
  <joint name="j_shoulder_mount" type="fixed">
    <parent link="base_link"/><child link="shoulder_housing"/>
    <origin xyz="0 0 0.030"/>
  </joint>

  <link name="upper_arm">
    <inertial>
      <origin xyz="0 0 -0.10"/>
      <mass value="0.030"/>
      <inertia ixx="1.0e-4" ixy="0" ixz="0" iyy="1.0e-4" iyz="0" izz="1.0e-6"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.10"/>
      <geometry><cylinder radius="0.008" length="0.20"/></geometry>
      <material name="arm_upper"><color rgba="0.9 0.6 0.1 1"/></material>
    </visual>
  </link>
  <joint name="shoulder_joint" type="revolute">
    <parent link="shoulder_housing"/><child link="upper_arm"/>
    <origin xyz="0 0 -0.010"/>
    <axis xyz="0 -1 0"/>
    <limit lower="-100" upper="100" effort="2.0" velocity="20"/>
    <dynamics damping="0.005" friction="0.001"/>
  </joint>

  <link name="forearm">
    <inertial>
      <origin xyz="0 0 -0.10"/>
      <mass value="0.030"/>
      <inertia ixx="1.0e-4" ixy="0" ixz="0" iyy="1.0e-4" iyz="0" izz="1.0e-6"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.10"/>
      <geometry><cylinder radius="0.008" length="0.20"/></geometry>
      <material name="arm_lower"><color rgba="0.1 0.6 0.9 1"/></material>
    </visual>
  </link>
  <joint name="elbow_joint" type="revolute">
    <parent link="upper_arm"/><child link="forearm"/>
    <origin xyz="0 0 -0.20"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="3.2" effort="2.0" velocity="20"/>
    <dynamics damping="0.005" friction="0.001"/>
  </joint>

  <link name="end_effector">
    <inertial><mass value="0.005"/>
      <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/></inertial>
    <visual><geometry><sphere radius="0.012"/></geometry>
      <material name="ee"><color rgba="0.10 0.95 0.25 1"/></material></visual>
    <collision><geometry><sphere radius="0.012"/></geometry></collision>
  </link>
  <joint name="j_ee" type="fixed">
    <parent link="forearm"/><child link="end_effector"/>
    <origin xyz="0 0 -0.20"/>
  </joint>
'''


def finger_block(idx, phi):
    """One M-segment finger at azimuth phi around the -z (palm) axis, mounted
    at the forearm tip (z=-0.20 in forearm frame). Segments named
    finger{idx}_seg{k}; each curls inward about the tangential axis."""
    c, s = math.cos(phi), math.sin(phi)
    mx, my = MOUNT_R * c, MOUNT_R * s
    # Joint axis is tangential so +angle curls the finger toward the -z axis.
    ax, ay = -s, c
    half = FINGER_HALF
    masses = [0.004, 0.0035, 0.003, 0.0025]   # proximal heaviest
    colors = ["0.85 0.85 0.20 1", "0.95 0.55 0.10 1",
              "0.20 0.45 0.95 1", "0.6 0.3 0.8 1"]
    out = []
    for k, L in enumerate(SEG_LENS):
        link = f"finger{idx}_seg{k}"
        parent = "forearm" if k == 0 else f"finger{idx}_seg{k-1}"
        origin = (f"{mx:.4f} {my:.4f} -0.20" if k == 0
                  else f"0 0 {-SEG_LENS[k-1]:.4f}")
        m = masses[min(k, len(masses) - 1)]
        col = colors[min(k, len(colors) - 1)]
        out.append(f'''
  <link name="{link}">
    <inertial><origin xyz="0 0 {-L/2:.4f}"/><mass value="{m}"/>
      <inertia ixx="3e-6" ixy="0" ixz="0" iyy="3e-6" iyz="0" izz="1e-6"/></inertial>
    <visual><origin xyz="0 0 {-L/2:.4f}"/>
      <geometry><box size="{2*half:.3f} {2*half:.3f} {L:.3f}"/></geometry>
      <material name="seg{idx}{k}"><color rgba="{col}"/></material></visual>
    <collision><origin xyz="0 0 {-L/2:.4f}"/>
      <geometry><box size="{2*half:.3f} {2*half:.3f} {L:.3f}"/></geometry></collision>
  </link>
  <joint name="{link}_joint" type="revolute">
    <parent link="{parent}"/><child link="{link}"/>
    <origin xyz="{origin}"/>
    <axis xyz="{ax:.4f} {ay:.4f} 0"/>
    <limit lower="-0.8" upper="2.0" effort="0.6" velocity="15"/>
    <dynamics damping="0.002" friction="0.001"/>
  </joint>''')
    return "".join(out)


def main():
    parts = [HEADER, PROPS, ARM]
    for i in range(N_FINGERS):
        parts.append(finger_block(i, 2 * math.pi * i / N_FINGERS + math.pi / 2))
    parts.append("</robot>\n")
    out = os.path.join(os.path.dirname(__file__), "quadrotor_gripper.urdf")
    with open(out, "w") as f:
        f.write("".join(parts))
    print(f"wrote {out}  ({N_FINGERS} fingers x {len(SEG_LENS)} segments, "
          f"reach ~{sum(SEG_LENS):.3f} m, pad friction {PAD_FRICTION})")


if __name__ == "__main__":
    main()
